### ISSUE TITLE
Call from fragment

### ISSUE THREAD

**Issue by OmarELRayes** [SimformSolutionsPvtLtd/SSImagePicker#20]
Can you modify it so i'm able to call it from a fragment ?

  ```
override fun onAttach(context: Context) {
        super.onAttach(context)
        mListener = if (context is ItemClickListener) {
            context
        } else {
            throw RuntimeException("$context")
        }
    }
```
the if condition always fails and throws RuntimeException
` imagePicker = ImagePickerActivityClass(requireContext(), requireActivity(), this, requireActivity().activityResultRegistry)
`

**Comment by PayalRajput-Simform** [comment]
Thank you for informing us about this issue. We have resolved your issue, so now you can use this in your fragment too by implementing latest version(1.6) of our library in your build.gradle .

**Comment by shwetachauhan-simform** [comment]
@OmarELRayes : Let us know your issue resolved or not. After that we will close this issue.

**Comment by OmarELRayes** [comment]
Yes it works, you also added it in the readme, thank you.
