### ISSUE TITLE
open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by ArisChoice** [SimformSolutionsPvtLtd/SSImagePicker#21]
file:/storage/emulated/0/Android/data/com.abc.customer/files/Pictures/JPEG_20210503_232332_6233313561642340468.jpg: open failed: ENOENT (No such file or directory)

Not able to get file from returned String 
Device Android 10

**Comment by PayalRajput-Simform** [comment]
We are providing uri of selected image in onResult() method. so can you please brief us about where you want to display that image or which method are you using to parse or load that image. It will give us clear idea about the issue which you are facing.

**Comment by shwetachauhan-simform** [comment]
Closing this issue. @ArisChoice : If you still have issue, let us know
