### ISSUE TITLE
Free Hand Cropping 

### ISSUE THREAD

**Issue by vedraj360** [SimformSolutionsPvtLtd/SSImagePicker#27]
Thanks for developing a useful library.
It would be really great if you add a new feature "free hand crop" where we can pick comers and adjust ratios.

**Comment by ShwetaChauhan18** [comment]
sure @vedraj360 we will check feasibility and update it ASAP. Thanks for your feedback.

**Comment by vedraj360** [comment]
@ShwetaChauhan18  I have created a pull request with this above feature.

**Comment by ShwetaChauhan18** [comment]
@vedraj360 : Thanks, we will review your PR.

**Comment by ShwetaChauhan18** [comment]
@vedraj360 : Please update your PR

**Comment by vedraj360** [comment]
Done can you check PR now.

**Comment by vedraj360** [comment]
Have you checked?

**Comment by ShwetaChauhan18** [comment]
@vedraj360 : Yes, our developer will check this then I will merge if all is OK

**Comment by vedraj360** [comment]
@ShwetaChauhan18 Great 👍

**Comment by PayalRajput-Simform** [comment]
Hello! @vedraj360 , Thanks for showing your interest to make our library better. But we can not accept your PR as we are already using one third-party library in this project for crop feature, we can't add another third-party library now. If you can raise PR for the same feature without using any thrid party library, then we are glad to accept that. Thank you.

**Comment by priyankj-simform** [comment]
Worked on the issue and a new version will be released soon after some additional changes. As of now closing the issue. We will update you soon with the new version.

**Comment by yashwantgowla-simform** [comment]
@vedraj360 New version has been released now. Checkout it:  https://github.com/SimformSolutionsPvtLtd/SSImagePicker/releases/tag/2.0
