### ISSUE TITLE
The application could not be installed: INSTALL_FAILED_CONFLICTING_PROVIDER

### ISSUE THREAD

**Issue by shafayatb** [SimformSolutionsPvtLtd/SSImagePicker#30]
If I already have an installed app with this library and I try to installed another app I am getting the following error

**The application could not be installed: INSTALL_FAILED_CONFLICTING_PROVIDER**

I think the authorities for the file provider in the manifest are the same so that why it is conflicting.

`android:authorities="com.app.imagepickerlibrary.provider"`

**Comment by shwetachauhan-simform** [comment]
@shafayatb : We will check and fix by tomorrow.
Thanks for reporting this issue

**Comment by PayalRajput-Simform** [comment]
@shafayatb: We have resolved the File provider authority issue. You can check it by updating our library version to 1.8
