### ISSUE TITLE
Permissions handling on android 11+

### ISSUE THREAD

**Issue by llastkrakw** [SimformSolutionsPvtLtd/SSImagePicker#37]
Hello, i have a xiaomi phone and recently my phone api as been updated to android 11. So now when i open the bottomsheet dialog with any trigger , he do his work but i don't have any access to a file. I make some chearch and i see that when you target android 11+ asking read and write permission they not sufficient to have the permissions. I don't know if i'm wrong. Thank you for reply this.

**Comment by ShwetaChauhan18** [comment]
@llastkrakw : Yes, this is issue and we will fix this ASAP.

**Comment by AndroidDev-Auction** [comment]
Hi! @llastkrakw , i have tried to reproduce same issue in Moto g60 and Mi mobile with Android 11 and unable to face any problem. Could you please provide us some more details like your smaprtphone model and name, logs from logcat. It will help us to debug the issue.

**Comment by abhishek-1-simform** [comment]
Hi! @llastkrakw, i have tried to reproduce same issue in Moto g60 and Mi mobile with Android 11 and unable to face any problem. Could you please provide us some more details like your smaprtphone model and name, logs from logcat. It will help us to debug the issue.

**Comment by llastkrakw** [comment]
Hello, the app is there https://github.com/llastkrakw/NeverNote, i didn't have special things in the stacktrace. i asked to somebody who have multiple device to download the app and test image picker , an they reply me that there is same issue in android 11+. I have Redmi 9 with china ROM. hope I'm not wasting your time. Thank you.

**Comment by ShwetaChauhan18** [comment]
@llastkrakw : Sure, we will check and update you ASAP

**Comment by priyankj-simform** [comment]
Worked on the issue and a new version will be released soon after some additional changes. As of now closing the issue. We will update you soon with the new version.

**Comment by llastkrakw** [comment]
Okay , great !

**Comment by yashwantgowla-simform** [comment]
@llastkrakw New version has been released now. Checkout it:  https://github.com/SimformSolutionsPvtLtd/SSImagePicker/releases/tag/2.0
