### ISSUE TITLE
[Enhancement] Multi Select in Gallery

### ISSUE THREAD

**Issue by nasserr** [SimformSolutionsPvtLtd/SSImagePicker#38]
I think multi select is mandatory futur for such great library. I love this library I think it only need that and it will be perfect. Thank you

**Comment by yashwantgowla-simform** [comment]
@nasserr Thanks for addressing this feature. We will definitely look into it in upcoming release.

**Comment by nasserr** [comment]
Thank you

**Comment by priyankj-simform** [comment]
We are also adding support for Android 13 to be more accessible for future OS releases.

**Comment by priyankj-simform** [comment]
Worked on the issue and a new version will be released soon after some additional changes. As of now closing the issue. We will update you soon with the new version.

**Comment by yashwantgowla-simform** [comment]
@nasserr New version has been released now. Checkout it:  https://github.com/SimformSolutionsPvtLtd/SSImagePicker/releases/tag/2.0

**Comment by nasserr** [comment]
Thank you !!!
