### ISSUE TITLE
Ucrop default settings

### ISSUE THREAD

**Issue by moslem7342** [SimformSolutionsPvtLtd/SSImagePicker#59]
hi thank you for this library
my English is not good  , i try to explain
i want to set crop 16:9 and disable changing by user 
and disable and hide rotating
one more thing1:
when i try to scale image with two finger , when my fingers are on the crop section , its not work (crop rectangle move , i want to scale image not move the crop rectangle  )  . i think it is better that crop rectangle fixed in and image can move and scale.
one more thing2:
when an activity run two ImagePicker  , the result function  **" fun onImagePick(uri: Uri?)"** must have a **"request code"**  to know where to use the uri
sorry for my english :)

**Comment by AshvinVavaliya** [comment]
Hi https://github.com/moslem7342
For first point : You can use below code for fixed aspect ratio and image scalable

```
setFreeStyleCropEnabled(false)
setAspectRatioOptions(0, AspectRatio(null, 16F, 9F))
```

and If you don't want to see the other functionality like rotation then you can use 

```
setHideBottomControls(true)
```
So your view is display like below image 
![Screenshot_1680062543](https://user-images.githubusercontent.com/16113993/228424042-393eb430-af0c-40f2-9fbc-99ae9b308e62.png)

For second point
We are not get you on second point so can you please add more clarification for that?

**Comment by AshvinVavaliya** [comment]
Hello [moslem7342](https://github.com/moslem7342)
Let me know, did you get your solution so I'll update the status of this issue.

**Comment by aban98** [comment]
hi AshvinVavaliya
When I asked the question, I failed to find the solution, I used another library
thank you  & close it

**Comment by moslem7342** [comment]
When I asked the question, I failed to find the solution, I used another library
thank you & close it
