### ISSUE TITLE
Support Activity

### ISSUE THREAD

**Issue by ManInTheWind** [SimformSolutionsPvtLtd/SSImagePicker#60]
**Is your feature request related to a problem? Please describe.**
Hi, thanks this awesome plugin and author's hard work! I wonder this awesome plugin if could support Activity,because now I want to using in Flutter. But in flutter, its using FlutterActivity which is only extends Activity.
![image](https://user-images.githubusercontent.com/32859126/221415259-67e77888-a351-4284-850f-72136b768f75.png)

I think the main problem is that I cannot register in Acitivity,the registerImagePicker is only support ComponentActivity or  Fragment. 
```java
    companion object {
        fun ComponentActivity.registerImagePicker(callback: ImagePickerResultListener): ImagePicker {
            return ImagePicker(callback, this)
        }

        fun Fragment.registerImagePicker(callback: ImagePickerResultListener): ImagePicker {
            return ImagePicker(callback, requireActivity())
        }
    }
```
thank you~

**Comment by AshvinVavaliya** [comment]
Hi [ManInTheWind](https://github.com/ManInTheWind),
We are working on it, If it is possible to replace the ComponentActivity to Activity then we will definitely replace it, otherwise you can use the fragment for that.

We will update you soon.

**Comment by AshvinVavaliya** [comment]
Hello [ManInTheWind](https://github.com/ManInTheWind)
Let me know, did you find any solution? If found, I could close to Jesus.

**Comment by AshvinVavaliya** [comment]
Hello @ManInTheWind  
Any updates? otherwise, I close this issue.

**Comment by AshvinVavaliya** [comment]
As of now not getting any reply yet. So I'm closing this issue.
